config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :friends do
    collection { post :import }
  end
  get 'home/index'
  get 'search' => 'friends#search'
  #root 'home#index'
  root 'friends#index'
  get 'exams' => 'exams#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :friends
    validates :category, uniqueness: true ,presence: true
end

app/models/friend.rb
class Friend < ApplicationRecord
require "csv"
require 'activerecord-import/base'
require  'activerecord-import/adapters/postgresql_adapter'

    validates :first_name, presence: true,
                length: {minimum: 5}
    validates :email, presence: true
    validates :last_name, presence: true
    validates :phone, presence: true,
                length: {maximum: 10}
    validates :gender, presence: true,
                 length: {maximum: 1}
                
    belongs_to :user
    belongs_to :category

    #def full_name
        #[first_name, last_name].join(' ')
    #end
    has_one_attached :image
    
    def self.to_csv 
        CSV.generate(headers: true) do |csv|
            csv << column_names
            all.each do |friend|
                csv << friend.attributes.values_at(*column_names)
            end
        end
    end
    
    def self.import(file)
        #friends = []
        CSV.foreach(file.path, headers: true) do |row|
            
            Friend.create! row.to_hash
         #friends << Friend.new(row.to_h)
        end
        #Friend.import friends,recursive: true
    end

        
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/exam_controller.rb
class ExamController < ApplicationController
    def index
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    def index
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends =  Friend.all
    @categories = Category.all
    cate = params[:cate]
    if !cate.nil?
      @friends = Friend.where(:category_id => cate)
    else
      @friends = Friend.all
    end

    respond_to do |format|
      format.html
      format.csv { send_data current_user.friends.to_csv }
    end
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
    #@categories = Category.all.map {|c| [c.category,c.id]} 


  end

  def search  
        @query = params[:search]
        @friends = current_user.friends.where("lower(first_name) LIKE ?", "%#{@query}%") 
  end
    
  

  # GET /friends/1/edit
  def edit
    #@categories = Category.all.map {|c| [c.category,c.id]} 

  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    #@friend.category_id = params[:category_id] 

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
         #@friend.category_id = params[:category_id]
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def import
    Friend.import(params[:file])
    redirect_to friends_path, notice:"Friends  Added Successfully"
  end
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit this Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id, :dob,  :category_id, :gender)
      

    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
    
    def sign_up_params
        params.require(:user).permit(:username, :mobnum, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :mobnum, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
    def first_name(friend)
        if @friend.gender == "M"
          "Mr. #{@friend.first_name}"
        else
            "Ms. #{@friend.first_name}"
        end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/Exam/index.html.erb
<h1>This is my rails exam</h1>

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% if user_signed_in? %>
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>
<% else %>
  <h1>Welcome</h1>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>
<h3> Contacts under this category </h3>
<% Friend.where(category_id: @category.id).each do |friend| %>
<p> <%= friend.first_name %>, 
 <%= friend.last_name %>, 
 <%= friend.email %>, 
 <%= friend.phone %>, 
 <%= friend.twitter %>,
 <%= friend.dob %> </p>


<% end %>



<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/exams/index.html.erb
<h1>This is my rails exam</h1>
<p>Hello</p>

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>
  <div class="field">
    <%= form.label :Gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :twitter %>
     <%= form.text_field :twitter %>
  </div>
  <div class="field">
    <%= form.label :dob %>
     <%= form.text_field :dob %>
  </div>
  
  <div class="field">
    <%= form.label :Category %>
    <%= form.select :category_id, Category.all.map {|c| [c.category,c.id]} %>
  </div>
  
  <div class ="field">
    <%= form.number_field :user_id,
    id: :friend_user_id, value: current_user.id, type: :hidden %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<% if user_signed_in? %>
 <h1>Contacts</h1>
 
  <table>
   <thead>
     <tr>
       <th>First name</th>
       <th>Last name</th>
       
       <th>Email</th>
       <th>Phone</th>
       <th>Twitter</th>
       <th>User Id</th>
       <th>DOB</th>
       <th colspan="3"></th>
     </tr>
   </thead>
   <tbody>
     <% @friends.each do |friend| %>
       <% if friend.user == current_user %>
        <tr>
          
          <td><%= friend.first_name%> </td>
          <td><%= friend.last_name %></td>
          
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <td><%= friend.user_id %></td>
          <td><%= friend.dob %></td>
          <td><%= link_to Category.find(friend.category_id).category, category_path(friend.category_id) %></td>
          <td><%= link_to 'Show', friend %></td>
          <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
          <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         
          
        </tr>
       <% end %>
     <% end %>
   </tbody>
 </table>
 <br>

 
  
 
 
 <h3>Download File</h3>
 
 <%= link_to "Report", friends_path(format: "csv"), class: 'btn btn-default' %>
 <h3>Import Friends</h3>
 <%= form_tag import_friends_path, multipart: true do %>
   <%= file_field_tag :file %>
   <%= submit_tag "upload friends" %>
 <% end %>
 <%= link_to 'New Friend', new_friend_path %>
  <% else %>
  <h1>Welcome</h1>
<% end %>
 
  
 

app/views/friends/new.html.erb
<h1>Add Contact</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/search.html.erb
 
<h3>Search Result</h3>  
<% @friends.each do |friend| %>  
<p><%= friend.first_name %>,
<%= friend.last_name %>,
<%= friend.email %>,
<%= friend.phone %>,
<%= friend.twitter %></p>
<% end %>

    

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Category: <%= @friend.category.category %></h1>
<p>
  <strong>First name:</strong>
  <%= first_name(@friend) %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @friend.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @friend.phone %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @friend.twitter %>
</p>
<p>
  <strong>DOB:</strong>
  <%= @friend.dob %>
</p>


<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Contacts App' ,root_path, class: "navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      
        
      </li>
      <li class="nav-item">
        <%= link_to "Contacts", friends_path, class: "nav-link" %>
        
      </li>
      
      <% if user_signed_in? %>
      
       <li class="nav-item">
         <%= link_to "Add Contact", new_friend_path, class: "nav-link" %>
        
       </li>
       <li class="nav-item">
         <%= link_to "Sign Out", destroy_user_session_path,  method: :delete, class: "nav-link" %>
        
       </li>
       <li class="nav-item">
         <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        
       </li>
            
        <li class="nav-item">
         <%= link_to "Categories", categories_path, class: "nav-link" %>
        
       </li>
       <li class="nav-item">
         <%= link_to "Search", search_path, class: "nav-link" %>
        
       </li>
      <% else %>
       <li class="nav-item">
         <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        
       </li>
       <li class="nav-item">
         <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        
       </li>
       
       
       
       
      <% end %> 
    </ul>
    <%= form_tag(search_path, :method => "get", class: 'navbar-form navbar-left') do %>  
    <div class="input-group">  
        <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
        <div class="input-group-btn">  
           <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
        </div>  
    </div>  
    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Welcome</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<html>
<html>
    <title>Friends App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     <%= render 'home/header' %>
     
     <div class="container">
       <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
    


  </body>
</html>